//Modelagem Cencosud Api Lib - Aplicação de biblioteca de apis e dependencias de componentes entre endpoints

Table User {
    id              int        [pk, increment]   // Primary Key
    name            varchar(255) [not null]       // Nome do usuário
    email           varchar(255) [not null, unique] // E-mail do usuário
    password        varchar(255) [not null]       
    is_deleted      boolean     [default: false, not null] 
}

Table Projeto {
    id              int         [pk, increment]   // Primary Key
    name            varchar(255) [not null, unique] // Nome do projeto
    description     text        
    is_deleted      boolean     [default: false, not null] 
    deleted_by      int         [ref: > User.id] // Foreign Key para User
    deleted_at      timestamp
    created_by      int         [ref: > User.id, not null] // Foreign Key para User
    created_at      timestamp   [default: `current_timestamp`]
    updated_by      int         [ref: > User.id] // Foreign Key para User
    updated_at      timestamp
}

Table ApiInstance {
    api_id          int         [pk, ref: > Api.id, not null] // Foreign Key para Api
    projeto_id      int         [pk, ref: > Projeto.id, not null] // Foreign Key para Projeto      
    is_deleted      boolean     [default: false, not null] 
}

Table Api {
    id              int         [pk, increment]   // Primary Key
    responsavel_tecnico_id int [ref: > User.id, not null] // Foreign Key para User
    name            varchar(255) [not null, unique] // Nome da API
    description     text        
    baseUrl         varchar(255) [not null]     
    version         varchar(50)   
    is_deleted      boolean     [default: false, not null]
    deleted_by      int         [ref: > User.id] // Foreign Key para User
    deleted_at      timestamp
    created_by     int         [ref: > User.id, not null] // Foreign Key para User
    created_at      timestamp   [default: `current_timestamp`]
    updated_by      int         [ref: > User.id] // Foreign Key para User
    updated_at      timestamp 
}


Table Endpoint {
    id              int         [pk, increment]   // Primary Key
    api_id          int         [ref: > Api.id, not null] // Foreign Key para a API
    path            varchar(255) [not null]      
    method          varchar(10)  [not null]       
    description     text         
    is_deleted      boolean     [default: false, not null] 
    deleted_by      int         [ref: > User.id] // Foreign Key para User
    deleted_at      timestamp
    created_by     int         [ref: > User.id, not null] // Foreign Key para User
    created_at      timestamp   [default: `current_timestamp`]
    updated_by      int         [ref: > User.id] // Foreign Key para User
    updated_at      timestamp
}

Table Component {
    id              int         [pk, increment]   // Primary Key
    name            varchar(255) [not null, unique] // Nome do componente
    type            ComponentType [not null]      // Tipo de componente baseado no enum ComponentType
    description     text         
    is_deleted      boolean     [default: false, not null]
    deleted_by      int         [ref: > User.id] // Foreign Key para User
    deleted_at      timestamp
    created_by     int         [ref: > User.id, not null] // Foreign Key para User
    created_at      timestamp   [default: `current_timestamp`]
    updated_by      int         [ref: > User.id] // Foreign Key para User
    updated_at      timestamp

}

Table ComponentInstance {
    endpoint_id     int         [pk, ref: > Endpoint.id, not null] // Foreign Key para Endpoint
    component_id    int         [pk, ref: > Component.id, not null] // Foreign Key para Component 
    is_deleted      boolean     [default: false, not null] 
}


Enum ComponentType {
    Procedure
    Function
    Middleware
    Validation
    DTO
    Security
    Configuration
    Response
}


//TABELAS DE AUDITORIA 

Table Audit {
    id              int         [pk, increment]   // Primary Key
    type            varchar(255) [not null]       // Tipo de ação
    entity          varchar(255) [not null]       // Entidade afetada
    action          varchar(255) [not null]       // Ação realizada
    changes         json        
    performed_by    int         [ref: > User.id, not null] // Foreign Key para User
    performed_at    timestamp   [default: `current_timestamp`] 
}